const products = [
  {
    id: 1,
    image: "https://www.cuisinart.com/dw/image/v2/ABAF_PRD/on/demandware.static/-/Sites-us-cuisinart-sfra-Library/default/dw42dcae51/images/recipe-Images/cafe-latte1-recipe_resized.jpg?sw=1200&sh=1200&sm=fit",
    proName: "Latte",
    price: "$5",
    tastingNotes: ["Hazelnut", "Vanilla", "Caramel"],
    origin: "Ethiopia",
    region: "Southern", 
    description: "A casual spot serving coffee, tea, pastries, and small snacks.",
  },
  {
    id: 2,
    image: "https://www.allrecipes.com/thmb/chsZz0jqIHWYz39ViZR-9k_BkkE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/8624835-how-to-make-a-cappuccino-beauty-4x3-0301-13d55eaad60b42058f24369c292d4ccb.jpg",
    proName: "Cappuccino",
    price: "$6",
    tastingNotes: ["Chocolate", "Nutty", "Citrus"],
    origin: "Colombia",
    region: "Western",
  },
  {
    id: 3,
    image: "https://www.sharmispassions.com/wp-content/uploads/2012/07/espresso-coffee-recipe022.jpg",
    proName: "Espresso",
    price: "$4",
    tastingNotes: ["Bitter", "Smoky", "Sweet"],
    origin: "Brazil",
    region: "Northern",
  },
  {
    id: 4,
    image: "https://majestycoffee.com/cdn/shop/articles/americano_misto.jpg?v=1684064972",
    proName: "Americano",
    price: "$3",
    tastingNotes: ["Smooth", "Bold", "Clean"],
    origin: "Guatemala",
    region: "Central",
  },
  {
    id: 5,
    image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/the_perfect_mocha_coffee_29100_16x9.jpg",
    proName: "Mocha",
    price: "$6",
    tastingNotes: ["Chocolate", "Rich", "Creamy"],
    origin: "Peru",
    region: "Southern",
  },
  {
    id: 6,
    image: "https://www.foodandwine.com/thmb/xQZv2CX6FO5331PYK7uGPF1we9Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Partners-Flat-White-FT-BLOG0523-b11f6273c2d84462954c2163d6a1076d.jpg",
    proName: "Flat White",
    price: "$5",
    tastingNotes: ["Velvety", "Creamy", "Nutty"],
    origin: "Kenya",
    region: "Eastern",
  },
  {
    id: 7,
    image: "https://emilylaurae.com/wp-content/uploads/2022/10/Caramel-macchiato-4.jpg",
    proName: "Macchiato",
    price: "$4",
    tastingNotes: ["Strong", "Sweet", "Caramel"],
    origin: "Honduras",
    region: "Western",
  },
  {
    id: 8,
    image: "https://realfood.tesco.com/media/images/Salted-caramel-Irish-coffee-1400x919-815e2b8b-098f-45fd-a32a-82d29aba1b9e-0-1400x919.jpg",
    proName: "Irish Coffee",
    price: "$7",
    tastingNotes: ["Whiskey", "Cream", "Sweet"],
    origin: "Ireland",
    region: "Northern",
  },
  {
    id: 9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw9YOhO5NhhsgYDperNllwL-Y-6T8WJapcgQ&s",
    proName: "Cortado",
    price: "$4",
    tastingNotes: ["Smooth", "Balanced", "Light"],
    origin: "Spain",
    region: "Western",
  },
  {
    id: 10,
    image: "https://www.recipetineats.com/uploads/2023/06/Affogato_0.jpg",
    proName: "Affogato",
    price: "$8",
    tastingNotes: ["Ice Cream", "Sweet", "Bold"],
    origin: "Italy",
    region: "Southern",
  },
  {
    id: 11,
    image: "https://cdn.pickuplimes.com/cache/a0/7c/a07c3bf35435bf16965e7b9b3b63e6a6.jpg",
    proName: "Cold Brew",
    price: "$5",
    tastingNotes: ["Refreshing", "Smooth", "Light"],
    origin: "Vietnam",
    region: "Southeastern",
  },
  {
    id: 12,
    image: "https://www.halfbakedharvest.com/wp-content/uploads/2021/08/Iced-Brown-Sugar-Latte-with-Shaken-Espresso-1.jpg",
    proName: "Iced Latte",
    price: "$5",
    tastingNotes: ["Vanilla", "Chilled", "Creamy"],
    origin: "Cambodia",
    region: "Eastern",
  },
  {
    id: 13,
    image: "https://simplyhomecooked.com/wp-content/uploads/2025/07/caramel-frappuccino-recipe-2.jpg",
    proName: "Caramel Frappe",
    price: "$6",
    tastingNotes: ["Caramel", "Ice", "Sweet"],
    origin: "USA",
    region: "Midwest",
  },
  {
    id: 14,
    image: "https://www.butteredsideupblog.com/wp-content/uploads/2024/01/Matcha-Coffee-Recipe-12-scaled.jpg",
    proName: "Matcha Latte",
    price: "$7",
    tastingNotes: ["Matcha", "Creamy", "Earthy"],
    origin: "Japan",
    region: "Kyoto",
  },
  {
    id: 15,
    image: "https://cdn.apartmenttherapy.info/image/upload/v1559215715/k/archive/f87c4eb3b5a5d1eeaf070a17d01d85f6adf4ba6d.jpg",
    proName: "Vanilla Sweet Cream",
    price: "$6",
    tastingNotes: ["Vanilla", "Smooth", "Sweet"],
    origin: "Costa Rica",
    region: "Central",
  },
  {
    id: 16,
    image: "https://foodwithfeeling.com/wp-content/uploads/2021/02/Honey-Latte-5-edited-500x500.jpg",
    proName: "Honey Oat Latte",
    price: "$6",
    tastingNotes: ["Honey", "Oat", "Smooth"],
    origin: "Rwanda",
    region: "Eastern",
  },
];

// Cafe listing
export const cafeListing = [
  {
    id: 1,
    name: "Sunrise Coffee",
    location: "Phnom Penh",
    image:
      "https://www.geckoroutes.com/wp-content/uploads/2020/06/phnom-penh-cambodia.jpg",
    description:
      "A cozy spot with aromatic coffee, fresh pastries, and free Wi-Fi. Perfect for brunch or casual meetings.",
    openingHours: "Mon-Sun: 7am - 8pm",
    contact: "+855 12 345 678",
    specialties: ["Latte", "Cold Brew", "Croissants"],
  },
  {
    id: 2,
    name: "Urban Brew",
    location: "Siem Reap",
    image:
      "https://i0.wp.com/thalias.com.kh/wp-content/uploads/2022/11/The-Best-of-Siem-Reap-at-your-Fingertips.jpeg?fit=1180%2C787&ssl=1",
    description:
      "Modern café with artisanal coffee and minimalist interior. Known for its friendly staff and quality espresso.",
    openingHours: "Mon-Fri: 6:30am - 7pm, Sat-Sun: 7am - 6pm",
    contact: "+855 63 234 567",
    specialties: ["Cappuccino", "Matcha Latte", "Bagels"],
  },
  {
    id: 3,
    name: "Leaf & Latte",
    location: "Battambang",
    image:
      "https://visitlocaltravel.com/blog/wp-content/uploads/2023/12/Battambang-Central-Market.png",
    description:
      "A relaxed café blending traditional flavors with modern coffee brewing techniques.",
    openingHours: "Daily: 7am - 9pm",
    contact: "+855 53 123 456",
    specialties: ["Flat White", "Espresso", "Cheesecake"],
  },
  {
    id: 4,
    name: "Sunrise Coffee",
    location: "Koh Kong",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a9/73/f1/song-saa-private-island.jpg?w=600&h=400&s=1",
    description:
      "Second branch of Sunrise Coffee with rooftop seating and city views.",
    openingHours: "Mon-Sun: 7am - 8pm",
    contact: "+855 12 987 654",
    specialties: ["Iced Latte", "Muffins", "Cold Brew"],
  },
  {
    id: 5,
    name: "Urban Brew",
    location: "Sihanoukville",
    image:
      "https://globalchinapulse.net/wp-content/uploads/2024/09/Rise_And_Fallen_Roun-Ry_Cambodia-4_1920.jpg",
    description:
      "Quiet café in the heart of the city, ideal for remote work or relaxing afternoons.",
    openingHours: "Mon-Fri: 6:30am - 7pm, Sat-Sun: 7am - 6pm",
    contact: "+855 63 765 432",
    specialties: ["Americano", "Croissants", "Iced Mocha"],
  },
  {
    id: 6,
    name: "Leaf & Latte",
    location: "Kirirom national park",
    image:
      "https://vet-groupresorts.com/wp-content/uploads/2024/08/romdoul-resort-1.jpg",
    description:
      "Popular local café with a cozy interior and variety of signature drinks.",
    openingHours: "Daily: 7am - 9pm",
    contact: "+855 53 654 321",
    specialties: ["Mocha", "Espresso", "Cheesecake"],
  },
];

export const Products = () => Promise.resolve(products);
export const CafeListing = () => Promise.resolve(cafeListing);